//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTTimeline.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class String_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACTTimeline.resources.String_EN", typeof(String_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Resource Directory
        ///( select directory include &quot;/timeline&quot; and &quot;/wav&quot;).
        /// </summary>
        public static string _LN_PleaseSelectResDir {
            get {
                return ResourceManager.GetString("_LN_PleaseSelectResDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Started.
        /// </summary>
        public static string _LN_PluginStarted {
            get {
                return ResourceManager.GetString("_LN_PluginStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Resource Dir! .
        /// </summary>
        public static string _LN_ResFound {
            get {
                return ResourceManager.GetString("_LN_ResFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources Not Found :/.
        /// </summary>
        public static string _LN_ResNotFound {
            get {
                return ResourceManager.GetString("_LN_ResNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show CD Timeline.
        /// </summary>
        public static string _LN_ShowTimeline {
            get {
                return ResourceManager.GetString("_LN_ShowTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT CD Timeline.
        /// </summary>
        public static string _LN_Tabname {
            get {
                return ResourceManager.GetString("_LN_Tabname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Found {0} timeline txt files..
        /// </summary>
        public static string _LN_TimelineFound {
            get {
                return ResourceManager.GetString("_LN_TimelineFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Timeline txt files dir not found!.
        /// </summary>
        public static string _LN_TimelineNotFound {
            get {
                return ResourceManager.GetString("_LN_TimelineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Found {0} Sound Files..
        /// </summary>
        public static string _LN_WavFound {
            get {
                return ResourceManager.GetString("_LN_WavFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sound files dir not found!.
        /// </summary>
        public static string _LN_WavNotFound {
            get {
                return ResourceManager.GetString("_LN_WavNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Font.
        /// </summary>
        public static string buttonFontSelect {
            get {
                return ResourceManager.GetString("buttonFontSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string buttonLoad {
            get {
                return ResourceManager.GetString("buttonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string buttonPause {
            get {
                return ResourceManager.GetString("buttonPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string buttonPlay {
            get {
                return ResourceManager.GetString("buttonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh List.
        /// </summary>
        public static string buttonRefreshList {
            get {
                return ResourceManager.GetString("buttonRefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string buttonResourceDirOpen {
            get {
                return ResourceManager.GetString("buttonResourceDirOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string buttonResourceDirSelect {
            get {
                return ResourceManager.GetString("buttonResourceDirSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Rewind.
        /// </summary>
        public static string buttonRewind {
            get {
                return ResourceManager.GetString("buttonRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move by drag &amp;&amp; right doubleclick to hide..
        /// </summary>
        public static string checkBoxMoveOverlayByDrag {
            get {
                return ResourceManager.GetString("checkBoxMoveOverlayByDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound by ACT.
        /// </summary>
        public static string checkBoxPlaySoundByACT {
            get {
                return ResourceManager.GetString("checkBoxPlaySoundByACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show mini button controls..
        /// </summary>
        public static string checkBoxShowOverlayButtons {
            get {
                return ResourceManager.GetString("checkBoxShowOverlayButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timelines.
        /// </summary>
        public static string groupBoxTimelines {
            get {
                return ResourceManager.GetString("groupBoxTimelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Width.
        /// </summary>
        public static string labelColumnSize {
            get {
                return ResourceManager.GetString("labelColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string labelFont {
            get {
                return ResourceManager.GetString("labelFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- No active timeline --.
        /// </summary>
        public static string labelLoadedTimeline {
            get {
                return ResourceManager.GetString("labelLoadedTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Timeline:.
        /// </summary>
        public static string labelLoadedTimelineLabel {
            get {
                return ResourceManager.GetString("labelLoadedTimelineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rows to display:.
        /// </summary>
        public static string labelNumRows {
            get {
                return ResourceManager.GetString("labelNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity:.
        /// </summary>
        public static string labelOpacity {
            get {
                return ResourceManager.GetString("labelOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Orientation.
        /// </summary>
        public static string labelOverlayOrientation {
            get {
                return ResourceManager.GetString("labelOverlayOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources Directory:.
        /// </summary>
        public static string labelResourceDir {
            get {
                return ResourceManager.GetString("labelResourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string tabMain {
            get {
                return ResourceManager.GetString("tabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tabOption {
            get {
                return ResourceManager.GetString("tabOption", resourceCulture);
            }
        }
    }
}
