//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTTimeline.resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String_KR() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACTTimeline.resources.String_KR", typeof(String_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   리소스 디렉토리를 선택하세요
        ///(선택한 폴더 아래에 &quot;/timeline&quot;폴더와 &quot;/wav&quot;폴더가 있어야 합니다.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _LN_PleaseSelectResDir {
            get {
                return ResourceManager.GetString("_LN_PleaseSelectResDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   플러그인이 정상적으로 시작되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _LN_PluginStarted {
            get {
                return ResourceManager.GetString("_LN_PluginStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리소스 디렉토리 찾음! 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _LN_ResFound {
            get {
                return ResourceManager.GetString("_LN_ResFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리소스를 찾을 수 없어요 ㅠㅁC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _LN_ResNotFound {
            get {
                return ResourceManager.GetString("_LN_ResNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACT 타임라인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _LN_Tabname {
            get {
                return ResourceManager.GetString("_LN_Tabname", resourceCulture);
            }
        }
        
        /// <summary>
        ///    {0}개의 타임라인 파일을 찾았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _LN_TimelineFound {
            get {
                return ResourceManager.GetString("_LN_TimelineFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    타임라인 폴더를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _LN_TimelineNotFound {
            get {
                return ResourceManager.GetString("_LN_TimelineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    {0}개의 사운드 파일을 찾았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _LN_WavFound {
            get {
                return ResourceManager.GetString("_LN_WavFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    사운드 폴더를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _LN_WavNotFound {
            get {
                return ResourceManager.GetString("_LN_WavNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글꼴 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buttonFontSelect {
            get {
                return ResourceManager.GetString("buttonFontSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buttonLoad {
            get {
                return ResourceManager.GetString("buttonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일시정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buttonPause {
            get {
                return ResourceManager.GetString("buttonPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buttonPlay {
            get {
                return ResourceManager.GetString("buttonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로고침과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buttonRefreshList {
            get {
                return ResourceManager.GetString("buttonRefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폴더열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buttonResourceDirOpen {
            get {
                return ResourceManager.GetString("buttonResourceDirOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buttonResourceDirSelect {
            get {
                return ResourceManager.GetString("buttonResourceDirSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   되감기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buttonRewind {
            get {
                return ResourceManager.GetString("buttonRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 허용 (체크 해제시 클릭 통과됨)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string checkBoxMoveOverlayByDrag {
            get {
                return ResourceManager.GetString("checkBoxMoveOverlayByDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACT를 통해 소리 재생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string checkBoxPlaySoundByACT {
            get {
                return ResourceManager.GetString("checkBoxPlaySoundByACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작은 컨트롤 버튼 보이기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string checkBoxShowOverlayButtons {
            get {
                return ResourceManager.GetString("checkBoxShowOverlayButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타임라인 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string groupBoxTimelines {
            get {
                return ResourceManager.GetString("groupBoxTimelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   행 너비과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelColumnSize {
            get {
                return ResourceManager.GetString("labelColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글꼴 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelFont {
            get {
                return ResourceManager.GetString("labelFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -- 불러온 타임라인 없음 --과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelLoadedTimeline {
            get {
                return ResourceManager.GetString("labelLoadedTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러온 타임라인 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelLoadedTimelineLabel {
            get {
                return ResourceManager.GetString("labelLoadedTimelineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보여질 열 갯수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelNumRows {
            get {
                return ResourceManager.GetString("labelNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   투명도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelOpacity {
            get {
                return ResourceManager.GetString("labelOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오버레이 위치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelOverlayOrientation {
            get {
                return ResourceManager.GetString("labelOverlayOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리소스 디렉토리 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelResourceDir {
            get {
                return ResourceManager.GetString("labelResourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타임라인 컨트롤과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblCtrl {
            get {
                return ResourceManager.GetString("lblCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타임라인 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타임라인 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblList {
            get {
                return ResourceManager.GetString("lblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일반과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabMain {
            get {
                return ResourceManager.GetString("tabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabOption {
            get {
                return ResourceManager.GetString("tabOption", resourceCulture);
            }
        }
    }
}
