//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTTimeline.resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class String_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String_EN() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACTTimeline.resources.String_EN", typeof(String_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Plugin Started과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _LN_PluginStarted {
            get {
                return ResourceManager.GetString("_LN_PluginStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACT Timeline과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _LN_Tabname {
            get {
                return ResourceManager.GetString("_LN_Tabname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Font과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string buttonFontSelect {
            get {
                return ResourceManager.GetString("buttonFontSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string buttonLoad {
            get {
                return ResourceManager.GetString("buttonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string buttonPause {
            get {
                return ResourceManager.GetString("buttonPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string buttonPlay {
            get {
                return ResourceManager.GetString("buttonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string buttonRefreshList {
            get {
                return ResourceManager.GetString("buttonRefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string buttonResourceDirOpen {
            get {
                return ResourceManager.GetString("buttonResourceDirOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string buttonResourceDirSelect {
            get {
                return ResourceManager.GetString("buttonResourceDirSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;&lt; Rewind과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string buttonRewind {
            get {
                return ResourceManager.GetString("buttonRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move by drag &amp;&amp; right doubleclick to hide.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string checkBoxMoveOverlayByDrag {
            get {
                return ResourceManager.GetString("checkBoxMoveOverlayByDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound by ACT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string checkBoxPlaySoundByACT {
            get {
                return ResourceManager.GetString("checkBoxPlaySoundByACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show mini button controls.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string checkBoxShowOverlayButtons {
            get {
                return ResourceManager.GetString("checkBoxShowOverlayButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timelines과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string groupBoxTimelines {
            get {
                return ResourceManager.GetString("groupBoxTimelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string labelColumnSize {
            get {
                return ResourceManager.GetString("labelColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string labelFont {
            get {
                return ResourceManager.GetString("labelFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -- No active timeline --과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string labelLoadedTimeline {
            get {
                return ResourceManager.GetString("labelLoadedTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loaded Timeline:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string labelLoadedTimelineLabel {
            get {
                return ResourceManager.GetString("labelLoadedTimelineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of rows to display:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string labelNumRows {
            get {
                return ResourceManager.GetString("labelNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string labelOpacity {
            get {
                return ResourceManager.GetString("labelOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay Orientation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string labelOverlayOrientation {
            get {
                return ResourceManager.GetString("labelOverlayOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resources Directory:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string labelResourceDir {
            get {
                return ResourceManager.GetString("labelResourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tabMain {
            get {
                return ResourceManager.GetString("tabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tabOption {
            get {
                return ResourceManager.GetString("tabOption", resourceCulture);
            }
        }
    }
}
